import { User, Request, Review, Notification, LocationTracking } from '../types';

export const mockUsers: User[] = [
  // Volunteers
  {
    id: 'vol-1',
    name: 'Sarah Thompson',
    email: 'sarah.thompson@email.com',
    role: 'volunteer',
    phone: '555-0101',
    address: '123 Volunteer Lane, Springfield',
    rating: 4.8,
    totalReviews: 24,
    joinedDate: '2024-06-15',
    stats: {
      totalRequests: 28,
      completedRequests: 24,
      activeRequests: 2,
    },
  },
  {
    id: 'vol-2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    role: 'volunteer',
    phone: '555-0102',
    address: '456 Helper Street, Springfield',
    rating: 4.9,
    totalReviews: 31,
    joinedDate: '2024-03-20',
    stats: {
      totalRequests: 35,
      completedRequests: 31,
      activeRequests: 1,
    },
  },
  {
    id: 'vol-3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@email.com',
    role: 'volunteer',
    phone: '555-0103',
    address: '789 Care Avenue, Springfield',
    rating: 4.7,
    totalReviews: 18,
    joinedDate: '2024-08-10',
    stats: {
      totalRequests: 20,
      completedRequests: 18,
      activeRequests: 0,
    },
  },
  // Seniors
  {
    id: 'sen-1',
    name: 'Margaret Smith',
    email: 'margaret.smith@email.com',
    role: 'senior',
    phone: '555-0201',
    address: '456 Oak Avenue, Springfield',
    joinedDate: '2024-05-01',
    stats: {
      totalRequests: 12,
      completedRequests: 10,
      activeRequests: 1,
    },
  },
  {
    id: 'sen-2',
    name: 'Robert Johnson',
    email: 'robert.johnson@email.com',
    role: 'senior',
    phone: '555-0202',
    address: '789 Medical Center Dr, Springfield',
    joinedDate: '2024-04-15',
    stats: {
      totalRequests: 8,
      completedRequests: 6,
      activeRequests: 1,
    },
  },
  {
    id: 'sen-3',
    name: 'Dorothy Williams',
    email: 'dorothy.williams@email.com',
    role: 'senior',
    phone: '555-0203',
    address: '321 Elm Street, Springfield',
    joinedDate: '2024-07-20',
    stats: {
      totalRequests: 5,
      completedRequests: 4,
      activeRequests: 1,
    },
  },
  // Admin
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@volunteerconnect.com',
    role: 'admin',
    phone: '555-0001',
    joinedDate: '2024-01-01',
  },
];

export const mockRequests: Request[] = [
  {
    id: 'req-1',
    title: 'Help with grocery shopping',
    description: 'I need help getting groceries from the local supermarket. I have a list of items ready and would appreciate someone to help me shop and carry the bags.',
    seniorId: 'sen-1',
    seniorName: 'Margaret Smith',
    status: 'pending',
    location: { address: '456 Oak Avenue, Springfield', lat: 40.7128, lng: -74.0060 },
    scheduledDate: '2025-11-09',
    scheduledTime: '10:00 AM',
    duration: '1-2 hours',
    createdAt: '2025-11-06T08:00:00Z',
    category: 'shopping',
    urgency: 'medium',
  },
  {
    id: 'req-2',
    title: 'Ride to medical appointment',
    description: 'I have a doctor\'s appointment and need a ride to the medical center. The appointment is at 2:30 PM and should take about an hour.',
    seniorId: 'sen-2',
    seniorName: 'Robert Johnson',
    status: 'pending',
    location: { address: '789 Medical Center Dr, Springfield', lat: 40.7580, lng: -73.9855 },
    scheduledDate: '2025-11-10',
    scheduledTime: '2:00 PM',
    duration: '2-3 hours',
    createdAt: '2025-11-06T10:30:00Z',
    category: 'transportation',
    urgency: 'high',
  },
  {
    id: 'req-3',
    title: 'Help setting up new phone',
    description: 'I just got a new smartphone and need help setting it up, transferring contacts, and learning how to use the basic features.',
    seniorId: 'sen-3',
    seniorName: 'Dorothy Williams',
    volunteerId: 'vol-1',
    volunteerName: 'Sarah Thompson',
    status: 'accepted',
    location: { address: '321 Elm Street, Springfield', lat: 40.7489, lng: -73.9680 },
    scheduledDate: '2025-11-11',
    scheduledTime: '11:00 AM',
    duration: '1 hour',
    createdAt: '2025-11-05T14:00:00Z',
    acceptedAt: '2025-11-05T16:30:00Z',
    category: 'technology',
    urgency: 'medium',
  },
  {
    id: 'req-4',
    title: 'Yard work assistance',
    description: 'Need help with some light yard work - raking leaves and tidying up the garden before winter.',
    seniorId: 'sen-1',
    seniorName: 'Margaret Smith',
    volunteerId: 'vol-2',
    volunteerName: 'Michael Chen',
    status: 'completed',
    location: { address: '456 Oak Avenue, Springfield', lat: 40.7128, lng: -74.0060 },
    scheduledDate: '2025-11-01',
    scheduledTime: '9:00 AM',
    duration: '2-3 hours',
    createdAt: '2025-10-28T09:00:00Z',
    acceptedAt: '2025-10-28T12:00:00Z',
    startedAt: '2025-11-01T09:00:00Z',
    completedAt: '2025-11-01T11:30:00Z',
    category: 'home-repair',
    urgency: 'low',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    requestId: 'req-4',
    reviewerId: 'sen-1',
    reviewerName: 'Margaret Smith',
    reviewerRole: 'senior',
    revieweeId: 'vol-2',
    revieweeName: 'Michael Chen',
    rating: 5,
    comment: 'Michael was wonderful! He worked so hard and left my yard looking beautiful. Very kind and patient.',
    createdAt: '2025-11-01T15:00:00Z',
  },
  {
    id: 'rev-2',
    requestId: 'req-4',
    reviewerId: 'vol-2',
    reviewerName: 'Michael Chen',
    reviewerRole: 'volunteer',
    revieweeId: 'sen-1',
    revieweeName: 'Margaret Smith',
    rating: 5,
    comment: 'Margaret was so welcoming and appreciative. It was a pleasure helping her.',
    createdAt: '2025-11-01T15:30:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'vol-1',
    title: 'Request Accepted',
    message: 'Your acceptance for "Help setting up new phone" has been confirmed. The task is scheduled for November 11, 2025 at 11:00 AM.',
    read: false,
    createdAt: '2025-11-05T16:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'vol-1',
    title: 'New Request Available',
    message: 'A new request "Help with grocery shopping" is available in your area. Check it out!',
    read: false,
    createdAt: '2025-11-06T08:05:00Z',
  },
  {
    id: 'notif-3',
    userId: 'sen-3',
    title: 'Volunteer Assigned',
    message: 'Sarah Thompson has accepted your request "Help setting up new phone". She will arrive on November 11, 2025 at 11:00 AM.',
    read: true,
    createdAt: '2025-11-05T16:30:00Z',
  },
];

export const mockLocationTracking: LocationTracking[] = [];